---
title: "Preliminary analysis"
author: "David Nguyen"
date: "April 7, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
```

```{r}
# source("Code/masterDataVARIABLES.R")
setwd("C://Users//david//Documents//STOICH//STOICH.Aim1//Code/DNguyen")
#write.csv(ALL_CNP, "ALL_CNP.csv", row.names = FALSE)
ALL_CNP <- read.csv("ALL_CNP.csv")
```

```{r}
head(ALL_CNP)
summary(ALL_CNP)

ALL_CNP %>% filter(NO3.as.N <= 0.0001)
```

```{r}
ALL_CNP %>% group_by(SITE_ID) %>% summarise(n_samples = n()) %>% ggplot() + stat_ecdf(aes(n_samples))
ALL_CNP %>% group_by()

ALL_CNP %>%
  ggplot() +
  geom_point(aes(x = log(DOC), y = log(NO3.as.N) , color = log(PO4.as.P)), alpha = 0.2) +
  scale_color_viridis() +
  facet_wrap(~ECO_TYPE)
```

# Fit model

Just going to fit model ignoring space and time

```{r}
head(ALL_CNP)
mod.fit.1 <- lm(log(NO3.as.N) ~ log(DOC)*ECO_TYPE + log(PO4.as.P)*ECO_TYPE, data = ALL_CNP)
summary(mod.fit.1)
```
```{r}
summary(mod.fit.1)$coefficients %>% data.frame() %>% rename("p value" = 4) %>% knitr::kable(digits = 3)
```


```{r}
plot(mod.fit.1)
```

```{r}
mod1_df <- mod.fit.1$model
mod1_df$fitted <- mod.fit.1$fitted.values
mod1_df$resid <- mod.fit.1$residuals
mod1_df$stdresid <- rstandard(mod.fit.1)
mod1_df$LON <- ALL_CNP$LON
mod1_df$LAT <- ALL_CNP$LAT

```

```{r}
mod1_df %>% 
  ggplot() + geom_point(aes(x = `log(DOC)`, y = stdresid)) + 
  geom_hline(yintercept = 0, linetype = "dashed", col = "red") +
  facet_wrap(~ECO_TYPE)
mod1_df %>% 
  ggplot() + geom_point(aes(x = `log(PO4.as.P)`, y = stdresid)) + 
  geom_hline(yintercept = 0, linetype = "dashed", col = "red") +
  facet_wrap(~ECO_TYPE)
```


### 3D plots

```{r}
library(plotly)
fig <- plot_ly(ALL_CNP, x = ~DOC, z = ~NO3.as.N, y = ~PO4.as.P, color = ~ECO_TYPE, colors = c('#BF382A', '#0C4B8E'))

fig <- fig %>% add_markers()

fig <- fig %>% layout(scene = list(xaxis = list(title = 'DOC', type = "log"),

                     zaxis = list(title = 'NO3', type = "log"),

                     yaxis = list(title = 'PO4', type = "log")))


fig
```

There are low DOC lakes and high DOC lakes. What causes these clusters?

```{r}
world <- map_data("world")

eu_nations <- c("Austria","Belgium","Bulgaria","Croatia","Cyprus",
                   "Czech Rep.","Denmark","Estonia","Finland","France",
                   "Germany","Greece","Hungary","Ireland","Italy","Latvia",
                   "Lithuania","Luxembourg","Malta","Netherlands","Poland",
                   "Portugal","Romania","Slovakia","Slovenia","Spain",
                   "Sweden","United Kingdom")

eu_map <- world %>% filter(region %in% eu_nations) %>% mutate(area = "EU")
us_map <- world %>% filter(region == "USA") %>% mutate(area = "USA")
us_eu_map <- rbind(eu_map, us_map)


ggplot() +
  geom_map(data = us_eu_map, map = us_eu_map,
           aes(long, lat, map_id = region),
           color = "white", fill = "lightgray") +
  geom_point(data = ALL_CNP %>% mutate(area = ifelse(LON < -30, "USA", "EU")), 
             mapping = aes(x = LON, y = LAT, color = log(DOC)), 
             alpha = 0.3) +
  facet_wrap(~area, scales = "free_x") +
  scale_color_viridis()


```

So, the very low DOC sites are all in the US.

```{r}
state_map <- map_data("state")

# plot lakes
ggplot() +
  geom_map(data = state_map, map = state_map,
           aes(long, lat, map_id = region),
           color = "white", fill = "lightgray") +
  geom_point(data = ALL_CNP %>% mutate(area = ifelse(LON < -30, "USA", "EU")) %>% filter(area == "USA", ECO_TYPE == "Lake"), 
             mapping = aes(x = LON, y = LAT, color = log(DOC)), 
             alpha = 0.3) +
  scale_color_viridis()

# plot river and stream
ggplot() +
  geom_map(data = state_map, map = state_map,
           aes(long, lat, map_id = region),
           color = "white", fill = "lightgray") +
  geom_point(data = ALL_CNP %>% mutate(area = ifelse(LON < -30, "USA", "EU")) %>% filter(area == "USA", ECO_TYPE != "Lake"), 
             mapping = aes(x = LON, y = LAT, color = log(DOC)), 
             alpha = 0.3) +
  scale_color_viridis()

```

### Spatial residuals

```{r}
ggplot() +
  geom_map(data = state_map, map = state_map,
           aes(long, lat, map_id = region),
           color = "white", fill = "lightgray") +
  geom_jitter(data = mod1_df %>% filter(LON < -50), 
             mapping = aes(x = LON, y = LAT, color = stdresid), 
             alpha = 0.3, size = 2) +
  scale_color_viridis() +
  labs(title = "Standardized residuals USA")

ggplot() +
  geom_map(data = eu_map, map = eu_map,
           aes(long, lat, map_id = region),
           color = "white", fill = "lightgray") +
  geom_jitter(data = mod1_df %>% filter(LON > -50), 
             mapping = aes(x = LON, y = LAT, color = stdresid), 
             alpha = 0.3, size = 2) +
  scale_color_viridis() +
  labs(title = "Standardized residuals EU")

```

